id: P3C68CA82
initial_creation_type: input
source_metadata:
  title: Dependent Origination
  language: es
  description: 'Texts on the subject of dependent origination (pratītyasamutpāda;
    rten cing ''brel bar ''byung ba) or interdependent arising:'
  volume:
    5828e148814b454c8eaa03210130dffc:
      title: The Noble Essence of Dependent Origination
      parent: Dhāraṇī
    6a180089ffcd471291bdc9dde0ee10d8:
      title: Commentary on Nāgārjuna's Verses on the Essence of Dependent Origination
      parent: Twelve Links
    8e2a3e389d0843a79bfced60fb6f6f0a:
      title: Commentary on the Noble Essence of the Dharmadhātu
      parent: Twelve Links
    98d48b6df59a4e5187e6d913aec13773:
      title: Verses on the Heart of Dependent Origination
      parent: Twelve Links
created_at: '2022-03-01T03:23:59.262939'
last_modified_at: '2022-03-01T03:23:59.262942'
